// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pryPlayers.DataAccess;

namespace pryPlayers.DataAccess.Migrations
{
    [DbContext(typeof(PlayersDBContext))]
    partial class PlayersDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("pryPlayers.DataAccess.Contracts.Entities.PlayerEntity", b =>
                {
                    b.Property<string>("idPlayer")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PLAid_player");

                    b.Property<string>("celular")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("PLAcelular");

                    b.Property<short>("estado")
                        .HasColumnType("smallint")
                        .HasColumnName("PLAestado");

                    b.Property<DateTime>("fechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("PLAfecha_modificacion");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("PLAfecha_registro");

                    b.Property<string>("lastname")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PLAlastname");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PLAname");

                    b.Property<short>("nivel")
                        .HasColumnType("smallint")
                        .HasColumnName("PLAnivel");

                    b.Property<int>("puntaje")
                        .HasColumnType("int")
                        .HasColumnName("PLApuntaje");

                    b.HasKey("idPlayer");

                    b.HasIndex("idPlayer");

                    b.ToTable("plaPLAtPlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
